version: '3.9'
services:
  node:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    volumes:
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
