version: '3.9'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: node
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    command: npm test
