version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Echo MONGODB_URI
          command: echo mongodb+srv://redpill:DNcajUKLY8bHiR37@cluster0.z3eyd.mongodb.net/myFirstDatabase?retryWrites=true&w=majority > .env
      - run:
          name: Cat env
          command: cat .env
      - run:
          name: Install npm dependenies
          command: npm ci
      - run:
          name: Run Tests
          command: npm test

workflows:
  run_test:
    jobs:
      - test