version: 2.1

executors:
  linux:
    docker:
      - image: cimg/base:2020.01

orbs:
  node: circleci/node@4.2.1
  slack: circleci/slack@4.4.0
  heroku: circleci/heroku@1.2.6

workflows:
  test-build-and-deploy:
    jobs:
      - test:
          context: Slack
          filters:
            branches:
              only:
                - development
                - production
          matrix:
            parameters:
              os: [linux]
              node-version: ["10.24.1", "12.22.1", "14.16.1", "15.14.0"]
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - production
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - production

jobs:
  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - run:
          name: Echo environment variables
          command: echo ${PROJECT_MONGODB_URI} > .env
      - node/install:
          node-version: << parameters.node-version >>
      - run:
          name: Install dependencies
          command: npm ci
      - run: npm test
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker
      - run:
         name: Build docker image
         command: make build-prod
  deploy:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - heroku/install
      - heroku/push-docker-image:
          app-name: ${PROJECT_HEROKU_APP}
