version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Echo MONGODB_URI
          command: echo $MONGODB_URI > .env
      - run:
          name: Install npm dependenies
          command: npm ci
      - run:
          name: Run Tests
          command: npm test

workflows:
  run_test:
    jobs:
      - test