version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Export environment variables to env
          command: echo ${PROJECT_MONGODB_URI} > .env
      - run:
          name: Install npm dependenies
          command: npm ci
      - run:
          name: Run Tests
          command: npm test

workflows:
  run_test:
    jobs:
      - test