version: 2.1

executors:
  linux:
    docker:
      - image: cimg/base:2020.01

orbs:
  node: circleci/node@4.2.1
  slack: circleci/slack@4.4.0
  heroku: circleci/heroku@1.2.6

jobs:
  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - run:
          name: Echo environment variables
          command: echo ${PROJECT_MONGODB_URI} > .env
      - node/install:
          node-version: << parameters.node-version >>
      - run:
          name: Install dependencies
          command: npm ci
      - run: npm test
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
  build-deploy:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.28.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Setup Environment Variables
          command: echo ${PROJECT_MONGODB_URI} > .env
      - run:
         name: Build docker image
         command: make build-prod
      - heroku/install
      - heroku/push-docker-image:
          app-name: tinfa-circle-ci
          api-key: PROJECT_HEROKU_API_KEY

workflows:
  version: 2
  test-build-and-deploy:
    jobs:
      - test:
          context: Slack
          # filters:
          #   branches:
          #     only:
          #       - development
          #       - production
          matrix:
            parameters:
              os: [linux]
              node-version: ["10.24.1", "12.22.1", "14.16.1", "15.14.0"]
      - build-deploy:
          requires:
            - test
          context: Slack
          # filters:
          #   branches:
          #     only:
          #       - production
