version: 2.1

orbs:
  node: circleci/node@4.1

workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: '10.x.x'
      - node/test:
          version: '12.x.x'
      - node/test:
          version: '14.x.x'
      - node/test:
          version: '15.x.x'
