version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14
    environment:
      MONGODB_URI: ${MONGODB_URI}
    steps:
      - checkout
      - run:
          name: Echo MONGODB_URI
          command: echo ${MONGODB_URI}
      - run:
          name: Install npm dependenies
          command: npm ci
      - run:
          name: Run Tests
          command: npm test

workflows:
  run_test:
    jobs:
      - test