version: 2.1

executors:
  linux:
    docker:
      - image: cimg/base:2020.01

orbs:
  node: circleci/node@4.2.1
  slack: circleci/slack@4.4.0

jobs:
  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - run:
          name: Echo environment variables
          command: echo ${PROJECT_MONGODB_URI} > .env
      - node/install:
          node-version: << parameters.node-version >>
      - run:
          name: Install dependencies
          command: npm ci
      - run: npm test
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  test-and-notify:
    jobs:
      - test:
          context: Slack
          matrix:
            parameters:
              os: [linux]
              node-version: ["10.24.1", "12.22.1", "14.16.1", "15.14.0"]