version: 2.1

executors:
  linux:
    docker:
      - image: cimg/base:2020.01

orbs:
  node: circleci/node@4.2.1
  slack: circleci/slack@4.4.0

jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - run:
          name: Echo environment variables
          command: echo ${PROJECT_MONGODB_URI} > .env
      - node/install:
          node-version: << parameters.node-version >>
      - run:
          name: Install dependencies
          command: npm ci
      - run: npm test

workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-secrets
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              os: [linux]
              node-version: ["10.24.1", "12.22.1", "14.16.1", "15.14.0"]